name: events that trigger a workflow v0.1
on:
  workflow_call:
  pull_request:
    types: [ closed, reopened, edited ]

jobs:
  triggers:
     runs-on: ubuntu-latest
     name: Runs on ${{ github.ref_name }}

     steps:
       - name: Checkout REPOSITORY_NAME
         uses: actions/checkout@v4

       - name: I was triggered by branch name
         run: |
           echo "You summoned me!"
           echo "You issued ${{ github.event }}"
